config/routes.rb
SimpleAd::Application.routes.draw do

  get "beta" => "home#beta", as: :beta

  root :to => 'home#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
  
  def beta
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/beta.html.haml
.hero-unit
  %h1 Ad Mouse is in private Beta
  %br
  %p If you're interested in being one of the first to try Ad Mouse, leave your email and we'll get in touch as soon as we're ready.
  
  = form_tag("/beta/join", method: "post", class: "from-inline") do
     
    .form-actions
      = text_field_tag :email, "", class: "input-xlarge", placeholder: "Enter Email Address" 
      = submit_tag "Join", class: "btn btn-primary btn-large span2"

app/views/home/show.html.haml
%h2.promo Drive customers, grow your business
.hero-unit
  %h1 Ad Mouse 
  %h2 Super Simple Online Marketing 
  
  %p
    Marketing your business online can be a frustrating experience. 
    %br
    Ad Mouse helps simplify the process by doing most of the work for you.
  %br
  %p 
    Plug in your Etsy Store, Ebay Store or Website and Ad Mouse will help take care of the rest. 
    
  
  = link_to "Get Started Today", beta_path, class: "btn btn-large btn-primary"
  
    
%hr.smooth.large
.row
  .span4
    %h2 Take the pain out of advertising online.
  .span4
    %h2
      Market your Etsy Store in minutes.
  
  .span4
    .ad-words
      = image_tag "adwords_logo.gif"
    %br
    .facebook
      = image_tag "facebook_logo.png"

%hr.smooth.large
  #how-does-it-work
    %h3 How does it work?
    %p
      Ad Mouse is built to help people with little or no technical experience market their business online.

    %h4 Getting Started
    %p
      Start by simply telling Ad Mouse what you want to market and Ad Mouse will guide you through the necessary steps to get you started. 
    %p 
      Ad Mouse will help you build your campaign  
      process of selecting key words, choosing an ad network and setting an ad budget. 

    %p When you're ready, say the command and Ad Mouse will get the process underway
    
    %h4 Tier 1 Ad Networks
    
    %p Ad Mouse is tightly integrated with Facebook and Google AdWords. Ad Mouse exists helps you navigate the complexities of setting up a campaign on one of these services.
    
    
    
    %h4 Monitoring Your Campaign
    %p
      When you're done Ad Mouse will help you keep track of your campaign progress, and give you meaningful metric so you can tell how well your campaign
      

  %hr.smooth.large      
  #pricing
  
    %h3 Low Risk Pricing
    
    %p
      Pricing for your ad campaigns depends on what you're advertising, where you're advertising, and how big the campaign is. Ad Mouse doesn't set the ad prices, but we do help you find the best and most cost effective pricing for your campaign.
    
    %h4 Ad Mouse keeps it simple. 
    
    %p Ad mouse charges a low 5% commission on all ad spend. 
    
    %p We only bill based on what you actually spend, so you won't pay a dime until you kick off your campaign. If you cancel your campaign mid-way through, we still only bill for what you spent. 
    
    %h4 Choose what you spend
    
    %p The size of your campaign is up to you, so you can choose spend as little or as much as you want. 
    
    %p What makes an effective marketing budgets really depends on what you're selling, but Ad Mouse will help predict the budget that works for you. 
    
    
    
    
    
    
  
  
  %hr.smooth.large
  #need-help
    %h3 Questions?&nbsp;&nbsp;We're here to help. 
    
    %p Drop us an email anytime and well get right back to you 
  
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleAd
    = stylesheet_link_tag    "application", :media => "all"
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      .container
        .row
          #logo.span3
            %a{href: root_path} 
              %h1 Ad Mouse

          .span9
            %nav
              #login
                = link_to "Sign In", "#", class: "btn btn-inverse"
              
              = link_to "Need help?", "#need-help", class: "nav"
              = link_to "Pricing", "#pricing", class: "nav"
              = link_to "How does it work?", "#how-does-it-work", class: "nav"
              
    #wrapper
      .container
        = yield

    %footer
      %p &copy; Ad Mouse 2012